#!/bin/sh

# get rid of temp files left laying around
rm -f php.in php.out php.test php.desc

# figure out how to echo with an end-of-line
if echo '\c' | grep -s c >/dev/null 2>&1
then
        ECHO_N="echo -n"
        ECHO_C=""
else
        ECHO_N="echo"
        ECHO_C='\c'
fi

# this is handy for debugging
$ECHO_N $ECHO_C "$1: "

unset REQUEST_METHOD CONTENT_TYPE REDIRECT_STATUS PATH_TRANSLATED QUERY_STRING
unset a b c d e             # array tests fail if these are in the environment

CMD=`awk -f testphp.awk $1`
eval $CMD

cat php.test | tr -d '\015' | awk '{ if(length($0)) print $0 }' > a.tmp
awk '{ if(length($0)) print $0 }' php.out >b.tmp
#rm -f php.test php.out

diff -w b.tmp a.tmp >/dev/null
ret=$?

if [ "$ret" = "1" ]; then
	echo " FAILED"
else
	echo " passed"
fi
exit $ret
