<?
  echo "getlastaccess: " . date("Y-m-d H:i:s", getlastaccess()) . "\n";
  echo "getlastbrowser: " . getlastbrowser() . "\n";
  echo "getlastemail: " . getlastemail() . "\n";
  echo "getlasthost: " . getlasthost() . "\n";
  echo "getlastref: " . getlastref() . "\n";
  echo "getlogdir: " . getlogdir() . "\n";
  echo "getstartlogging: " . date("Y-m-d H:i:s", getstartlogging()) . "\n";
  echo "gettoday: " . gettoday() . "\n";
  echo "gettotal: " . gettotal() . "\n";
?>
