<?php 
  error_reporting(0);
  $a[0]="a";
  $a[1]="b";
  $a[2]="c";

  reset($a);
  $key=key($a);
  $data=current($a);
  while ("" != (string) $key):
    echo "KEY: $key, VAL: $data\n";
    $data = next($a);
    $key=key($a);
  endwhile;

?>
<HR>
<?php 
  unset ($a);
  $key=key($a);
  $data = current($a);
  while ("" != (string) $key):
    echo "KEY: $key, VAL: $data\n";
    $data = next($a);
    $key= key($a);
  endwhile;
  unset($a);

?>
<HR>
<?php 
  $a[0]="d";
  $a[1]="e";
  $a[2]="f";

  reset($a);
  $key=key($a);
  $data = current($a);
  while ("" != (string) $key):
    echo "KEY: $key, VAL: $data\n";
    $data=next($a);
    $key=key($a);
  endwhile;
?>
<HR>
<?php 
  unset($a);
  $key=key($a);
  $data=current($a);
  while ("" != (string) $key):
    echo "KEY: $key, VAL: $data\n";
    $data=next($a);
    $key=key($a);
  endwhile;
  unset($a);
?>
<HR>
<?php 
  $a[]="g";
  $a[]="h";
  $a[]="i";

  reset($a);
  $key=key($a);
  $data=current($a);
  while ("" != (string) $key):
    echo "KEY: $key, VAL: $data\n";
    $data=next($a);
    $key=key($a);
  endwhile;
?>
<HR>
<?php 
  unset ($a);
  $key=key($a);
  $data=current($a);
  while ("" != (string) $key):
    echo "KEY: $key, VAL: $data\n";
    $data=next($a);
    $key=key($a);
  endwhile;
  unset($a);
?>
<HR>
<?php 
  $a[]="j";
  $a[]="k";
  $a[]="l";

  $key=key($a);
  $data=current($a);
  while ("" != (string) $key):
    echo "KEY: $key, VAL: $data\n";
    $data=next($a);
    $key=key($a);
  endwhile;
?>
