<HR> Assign Index from 0, then Auto assign
<?php 
  $z[0]="a";
  $z[1]="b";
  $z[2]="c";

  $z[]="d";
  $z[]="e";
  $z[]="f";

  $key= key($z);
  $data=current($z);
  while ("" != (string)$key):
    echo "KEY: $key, VAL: $data\n";
    $data=next($z);
    $key= key($z);
  endwhile;

  $cz= count($z);
  echo "count(): $cz\n";
?>
<HR> Assign Index from 1, then Auto assign
<?php 
  $a[1]="a";
  $a[2]="b";
  $a[3]="c";

  $a[]="d";
  $a[]="e";
  $a[]="f";

  $key= key($a);
  $data=current($a);
  while ("" != $key):
    echo "KEY: $key, VAL: $data\n";
    $data=next($a);
    $key= key($a);
  endwhile;

  $ca= count($a);
  echo "count(): $ca\n";
?>
<HR> Assign Index from 2, then Auto assign
<?php 
  $b[2]="a";
  $b[3]="b";
  $b[4]="c";

  $b[]="d";
  $b[]="e";
  $b[]="f";

  $key= key($b);
  $data=current($b);
  while ("" != $key):
    echo "KEY: $key, VAL: $data\n";
    $data=next($b);
    $key= key($b);
  endwhile;

  $cb= count($b);
  echo "count(): $cb\n";
?>
<HR> Assign Index from 3, then Auto assign
<?php 
  $c[3]="a";
  $c[4]="b";
  $c[5]="c";

  $c[]="d";
  $c[]="e";
  $c[]="f";

  $key= key($c);
  $data=current($c);
  while ("" != $key):
    echo "KEY: $key, VAL: $data\n";
    $data=next($c);
    $key= key($c);
  endwhile;

  $cc= count($c);
  echo "count(): $cc\n";
?>
<HR> Assign Index from 4, then Auto assign
<?php 
  $d[4]="a";
  $d[5]="b";
  $d[6]="c";

  $d[]="d";
  $d[]="e";
  $d[]="f";

  $key= key($d);
  $data=current($d);
  while ("" != $key):
    echo "KEY: $key, VAL: $data\n";
    $data=next($d);
    $key= key($d);
  endwhile;

  $cd= count($d);
  echo "count(): $cd\n";
?>
<HR> Assign Index from 5, then Auto assign
<?php 
  $e[5]="a";
  $e[6]="b";
  $e[7]="c";

  $e[]="d";
  $e[]="e";
  $e[]="f";

  $key= key($e);
  $data=current($e);
  while ("" != $key):
    echo "KEY: $key, VAL: $data\n";
    $data=next($e);
    $key= key($e);
  endwhile;

  $ce= count($e);
  echo "count(): $ce\n";
?>
<HR> Assign Index from 6, then Auto assign
<?php 
  $f[6]="a";
  $f[7]="b";
  $f[8]="c";

  $f[]="d";
  $f[]="e";
  $f[]="f";

  $key= key($f);
  $data=current($f);
  while ("" != $key):
    echo "KEY: $key, VAL: $data\n";
    $data=next($f);
    $key= key($f);
  endwhile;

  $cf= count($f);
  echo "count(): $cf\n";
?>
<HR> Assign Index from 7, then Auto assign
<?php 
  $g[7]="a";
  $g[8]="b";
  $g[9]="c";

  $g[]="d";
  $g[]="e";
  $g[]="f";

  $key= key($g);
  $data=current($g);
  while ("" != $key):
    echo "KEY: $key, VAL: $data\n";
    $data=next($g);
    $key= key($g);
  endwhile;

  $cg= count($g);
  echo "count(): $cg\n";
?>
