<html><head><title>PHP/FI FAQ</title>
</head>
<body background="/php/marb18.jpg" bgcolor="#FFFFFF" text="#000000" link="#0000FF" vlink="#000090" alink="FF0000">
<p align=center><img src="/php/gifs/flag.gif" height=30 width=30 alt=""><img src="/php/gifs/phpfi-blk.gif"height=43 width=153 alt="PHP/FI"><img src="/php/gifs/flag.gif" height=30 width=30 alt="">
<p align=center><font size=+2><tt><b>PHP/FI FAQ</b></tt></font></p>

<dl>
<dt><font size=+1>1. Why do I keep getting a parser error in a while loop?</font>
<dd>The parser is a bit sensitive to non-Unix line terminators.  You probably
created your file on a non-Unix box and uploaded it without converting the
file.  Most ftp programs have an option to convert ASCII files during the
transfer.  Alternatively, most Unix system will have a <i>dos2unix</i>
command which can convert the file for you.  If neither works for you, then
try typing the following from your Unix prompt:<br>
<tt>tr -d '\r' <filename >newfile</tt><p>

<dt><font size=+1>2. How do I substitute CR and LF characters using the reg_replace function?</font>
<dd>Any character can be replaced using its ASCII code.  A carriage return has ASCII 
code 13, so the following will do the trick: <br>
<tt>$string = reg_replace(13,"&lt;br&gt;",$string);</tt><br>
This will replace all carriage returns with HTML break tags.<p>

<dt><font size=+1>3. How do I get the GD image library to be recognized by the install program?</font>
<dd>The install program asks for extra directories to search for libraries
and include files in.  Make sure you specify the directory where you installed
the libgd.a file when it asks for libraries and the directory where the
gd*.h are located when it asks for extra directories.<p>

<dt><font size=+1>4. I am using mSQL logging, and my counters are stuck at 0.  Why?</font>
<dd>You haven't created the logging table for the user who owns that
particular HTML file.  Run the msqllog script found in the scripts directory
of the PHP/FI distribution.  <tt>msqllog username</tt> should do the trick
for you.<p>

<dt><font size=+1>5. How do I turn off the footer information at the bottom of my pages?</font>
<dd>If you simply want to turn it off on a page here and there, add the
tag: &lt;setshowinfo(0)&gt; to each page.  Alternatively, you can create
a &quot;No Info&quot; rule from the ?config screen.  If you are using the
Apache module version, you can add a line like:<br>
<tt>phpShowInfo off</tt><br>
to your <i>srm.conf</i> file, or directly to your <i>.htaccess</i> files.<p>

<dt><font size=+1>6. I am having all sorts of problems with logging and/or dbm files.</font>
<dd>Make sure you compiled in a decent dbm library.  I suggest you use gdbm
available from <a href="ftp://prep.ai.mit.edu/pub/gnu/gdbm-1.7.3.tar.gz">
prep.ai.mit.edu</a><p>

<dt><font size=+1>7. Why is the php.cgi/httpd binary so large?</font>
<dd>It is created with debugging symbols by default.  Type:<br>
<tt>strip php.cgi</tt> or <tt>strip httpd</tt><br>
to get it down to a more manageable size.<p>

<dt><font size=+1>8. How do I handle SELECT MULTIPLE form fields?</font>
<dd>The problem here is that a single form component can take on multiple
values.  This means you need to use an array.  A tag like the following
is what you want:<br>
   &lt;SELECT MULTIPLE name=&quot;var[]&quot;&gt;<br>
When you receive the submitted form, the $var array will contain all the
data.  Use a loop to fetch it.<p>

<dt><font size=+1>9. How do I refer to the current URL in a script?</font>
<dd>Use the $PHP_SELF variable.  Check the ?info screen for a full list of
available variables.  (Only available in version 1.99n and up)<p>
<?include "footer">
</body></html>
