#!/bin/sh
UUID=`id $1 | cut -d= -f2 | cut -d\( -f1`
if [ "$UUID" = "0" ]
  then
	echo -n "Username: "
	read UUID
	if grep "^$UUID\:.*\:.*\:.*\:.*\:.*\:.*" /etc/passwd > /dev/null
	  then
		echo "Username: $UUID, getting UID..."
		USERNAME=$UUID
		UUID="`grep \"^$UUID\:.*\:.*\:.*\:.*\:.*\:.*\" /etc/passwd \
                        | gawk -F : '{print $3}'`"
		echo "Done. $USERNAME = $UUID ."
	fi
	echo ''
	echo -n Want to continue '(y/n)'?
	read want
	if [ "$want" = "n" ]
	  then
		exit 10
	fi
fi


echo "Creating tables for user id $UUID..."
/usr/local/bin/mysql phpfi <<EOF
CREATE TABLE log$UUID (
	timestmp	INT,
	filename	CHAR(64),
	host		CHAR(64),
	email		CHAR(64),
	lref		CHAR(64),
	browser		CHAR(64),
	KEY (filename)
);

CREATE TABLE last$UUID (
	filename CHAR(64) NOT NULL,
  	timestmp INT NOT NULL,
  	total INT,
  	today INT,
  	stimestamp INT NOT NULL,
  	host CHAR(64),
  	email CHAR(64),
  	lref CHAR(64),
  	browser CHAR(64),
  	PRIMARY KEY (filename)
);

EOF
